trigger: [main]
pr: [main]
schedules:
  - cron: "0 0 * * 1"
    displayName: "Weekly: cookie-doh"
    branches:
      include:
        - main
pool:
  vmImage: ubuntu-latest
steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      showAlertLink: true
      failOnAlert: true
      failOnStderr: true
      logLevel: debug
